#!/usr/bin/env node
/**
 * Run ONCE locally to download the full NSE equity list and generate src/nseDb.js
 * Usage:  node scripts/downloadNseDb.mjs
 *
 * If the auto-fetch fails (NSE Akamai block), use the manual fallback:
 *   1. Open https://archives.nseindia.com/content/equities/EQUITY_L.csv in your browser
 *   2. Save the file as EQUITY_L.csv in the project root
 *   3. node scripts/downloadNseDb.mjs --file ./EQUITY_L.csv
 *
 * Re-run monthly to keep the list fresh.
 */

import https from 'https';
import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../src/nseDb.js');

function get(url, extraHeaders = {}) {
  return new Promise((resolve, reject) => {
    https.get(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'identity',
        ...extraHeaders,
      },
    }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location)
        return get(res.headers.location, extraHeaders).then(resolve).catch(reject);
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve({ status: res.statusCode, body: Buffer.concat(chunks).toString('utf8'), headers: res.headers }));
    }).on('error', reject).setTimeout(20000, function(){ this.destroy(); reject(new Error('timeout')); });
  });
}

function parseCsv(text) {
  const lines = text.split(/\r?\n/).filter(l => l.trim());
  if (lines.length < 2) return [];
  const hdr     = lines[0].split(',').map(h => h.replace(/"/g,'').trim().toUpperCase());
  const symIdx  = hdr.findIndex(h => h === 'SYMBOL');
  const nameIdx = hdr.findIndex(h => h.includes('NAME'));
  const secIdx  = hdr.findIndex(h => h.includes('INDUSTRY') || h.includes('SECTOR'));
  if (symIdx < 0) { console.error('No SYMBOL column. Headers:', hdr); return []; }
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const p = lines[i].split(',').map(x => x.replace(/^"|"$/g,'').trim());
    const sym = (p[symIdx]||'').toUpperCase();
    if (!sym) continue;
    out.push({ sym, name: p[nameIdx]||sym, sector: secIdx>=0 ? (p[secIdx]||'') : '' });
  }
  return out;
}

async function main() {
  // --file mode: use a manually downloaded CSV
  const fileIdx = process.argv.indexOf('--file');
  if (fileIdx !== -1) {
    const filePath = process.argv[fileIdx + 1];
    console.log('Reading CSV from', filePath);
    const rows = parseCsv(fs.readFileSync(filePath, 'utf8'));
    write(rows);
    return;
  }

  // Auto-fetch: needs a valid NSE session cookie
  console.log('Fetching NSE homepage for session cookie…');
  const home = await get('https://www.nseindia.com/');
  const cookies = [].concat(home.headers['set-cookie']||[]).map(c=>c.split(';')[0]).join('; ');
  console.log('  Status:', home.status, ' Cookie length:', cookies.length);

  console.log('Fetching EQUITY_L.csv…');
  const csv = await get('https://archives.nseindia.com/content/equities/EQUITY_L.csv', {
    Referer: 'https://www.nseindia.com/',
    Cookie: cookies,
  });
  console.log('  Status:', csv.status, ' Body length:', csv.body.length);

  if (csv.status !== 200 || csv.body.trim().startsWith('<')) {
    console.error('\n✗ Auto-fetch failed. NSE is blocking server-side requests.');
    console.error('  Manual steps:');
    console.error('  1. Open this URL in your browser (while logged into NSE or just as-is):');
    console.error('     https://archives.nseindia.com/content/equities/EQUITY_L.csv');
    console.error('  2. Save file to project root as EQUITY_L.csv');
    console.error('  3. Run: node scripts/downloadNseDb.mjs --file ./EQUITY_L.csv\n');
    process.exit(1);
  }

  write(parseCsv(csv.body));
}

function write(rows) {
  if (!rows.length) { console.error('No rows parsed.'); process.exit(1); }
  const js = `// Auto-generated by scripts/downloadNseDb.mjs — do not edit manually.
// Refresh: node scripts/downloadNseDb.mjs   (or --file ./EQUITY_L.csv)
// Generated: ${new Date().toISOString().slice(0,10)}   Stocks: ${rows.length}
export const NSE_FULL_DB = ${JSON.stringify(rows)};
`;
  fs.writeFileSync(OUT, js, 'utf8');
  console.log(`\n✓ ${rows.length} stocks written to ${OUT}`);
}

main().catch(e => { console.error('Error:', e.message); process.exit(1); });
