// Auto-generated by scripts/downloadNseDb.mjs
// Run: node scripts/downloadNseDb.mjs --file ./EQUITY_L.csv
// Until then the app uses the built-in fallback list in App.jsx
export const NSE_FULL_DB = [];
